services:   # Check HERE: https://github.com/mongo-express/mongo-express/issues/518
# https://github.com/docker-library/mongo/issues/475
# https://www.mongodb.com/docs/manual/tutorial/deploy-replica-set-with-keyfile-access-control/
#  THIS LINK IS ESSENTIAL: https://gist.github.com/harveyconnor/518e088bad23a273cae6ba7fc4643549
  
  # To create the key for the replica set do: openssl rand -base64 756 > replica.key
  queries:
    env_file: "../.env"
    depends_on:
      - longdb1
      - longdb2
      - longdb3
    build: .
    restart: on-failure
    ports:
      - $QUERIES_PORT:$QUERIES_PORT
    networks:
      - long_term_db_network

  # Primary
  longdb1:
    image: mongo:latest
    container_name: longdb1
    restart: always
    env_file: "../.env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}  # Database to be created on startup
    ports:
      - ${MONGODB_PORT1}:27017 # Port changed due to possible conflict with MongoDb on local
    depends_on:
      - longdb2
      - longdb3
    volumes:
      - ../key/replica.key:/data/replica.key
      #- ./mongo-queries:/data/db //TODO: Define the Volume where to mount the DB.
    networks:
      - long_term_db_network
    command: ["mongod", "--replSet", "replicaSet", "--keyFile", "/data/replica.key", "--bind_ip_all"]

  # Secondary
  longdb2:
    image: mongo:latest
    container_name: longdb2
    restart: always
    env_file: "../.env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}  # Database to be created on startup
    ports:
      - ${MONGODB_PORT2}:27017
    volumes:
      - ../key/replica.key:/data/replica.key
      #- ./mongo-queries:/data/db //TODO: Define the Volume where to mount the DB.
      #- ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro  # Mount init scripts folder
    networks:
      - long_term_db_network
    command: ["mongod", "--replSet", "replicaSet", "--keyFile", "/data/replica.key", "--bind_ip_all"]


  # Arbiter
  longdb3:
    image: mongo:latest
    container_name: longdb3
    restart: always
    env_file: "../.env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}  # Database to be created on startup
    ports:
      - ${MONGODB_PORT3}:27017
    volumes:
      - ../key/replica.key:/data/replica.key
      #- ./mongo-queries:/data/db //TODO: Define the Volume where to mount the DB.
    networks:
      - long_term_db_network
    command: ["mongod", "--replSet", "replicaSet", "--keyFile", "/data/replica.key", "--bind_ip_all"]



  mongo-setup:
    image: mongo:latest
    container_name: mongo-setup
    restart: on-failure
    env_file: "../.env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - longdb1
      - longdb2
      - longdb3
    volumes:
      - ../mongo-init/mongodb_init.sh:/scripts/mongodb_init.sh
    networks:
      - long_term_db_network
    entrypoint: ["/bin/bash", "/scripts/mongodb_init.sh"] 

networks:
  long_term_db_network:
    driver: bridge