# TODO: The longTermDB needs to be created outside the queries service because
# it will be accessible also by matchmaker and game server manager, but each 
# service can create its own collection.
services:
  longdb:
    image: mongo:latest
    container_name: longdb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}  # Database to be created on startup
    ports:
      - "27018:27017" # Port changed because possible conflict with MongoDb on local
    volumes:
      #- ./mongo-auth:/data/db //TODO: Define the Volume where to mount the DB.
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro  # Mount init scripts folder
    networks:
      - long_term_db_network

  mongo-express-queries:
    image: mongo-express:latest
    container_name: mongo-express-queries
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@longdb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "8082:8081"
    depends_on:
      - longdb
    networks:
      - long_term_db_network

networks:
  long_term_db_network:
    driver: bridge