apiVersion: apps/v1
kind: Deployment
metadata:
  name: queries-service
  labels:
    app: pacman-game
spec:
  selector:
    matchLabels:
      app: pacman-game
      role: queries-service
  replicas: 1
  template:
    metadata:
      labels:
        app: pacman-game
        role: queries-service
    spec:
      containers:
        - name: queries-service
          image: queries-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: AUTHENTICATOR
              value: "http://authenticator-service:8080"
