# Defines the username and password of root user.
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: authdb-secret
  namespace: authdb
data:
  # admin in Base64
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  # password in Base64
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=
  # ./replica.key in Base64
  # replica_key: K3QxQkNVKy9TeGR2YjE0aUJ4Y1JKc1FUcEpGZXFnZkNJUmc4VVJvT3VycDdOdEpSM0pxNkM1NjMxS2lvMWh4VQ0KZ2dmSlN2S0NveU5DeE9XWWdLUGhya2pobGdib3FzTStyQkR4M3R5RzBpRlFROWFIcnYzT2llRmJFMXVJT0tJcA0KcXZEY3creFVBenAwY1g4MjJVUU9tZURMUFBxMElhalRndGN3bGdQYVhWU2lwSXFvY2ZVQlhGOGpBMTByTGl0Zw0KNW5xVGFXaUNvbFEyTEZSNlAwNS80VzBGVXlINWhSeXdJelRENnR3aVhTMHBwY00vS0VidHMrSzkxSUM5UWVXTg0KYUFSWm9QdUxQQXN3NklnR0hSN3NqQ1creEgzZ1hMdnhxdDdPZWh4L1ZhN2FQMlFTYUM0cnhBRUtyMUp3YVZhbQ0KVE5LZzJ0NlNhMUtOWlhmS3hDYXoxUkIrbDBDOWtPT2pUcDdIbUxnODJFaHNYa2swQlZGT3Z1R2pxWnFQcDlzMA0KRmhrMUwxYVZFenZ3bGRpc0FmT0ZHdmZ0bVBYSHhwaFZqQmlRRmFXWnRUdWZGRTVDVkpaVGlRSVJOL0dMb1hYeQ0KaEI3RHdzT29NRnRKbmZ5S1R1ZkREQTVjYi9jZUdFdnlKaU1jM256WjBmMnd6MkcvcUNNdWtPbnpScTBsaUM5dQ0KU0JIVW1HenhRWjZObGFtL2s1eHV6RWJ5czltZ3B5dzdrMGVLa1AzMzBUZXh0U0pwWFZTaXoyM1VxRCs4RlZGeQ0Ka1VBNnFMcEEzemF0aTZCUG5rTXZSWWZHT29WMi9jUll0TzhvVWo3TVpTK0JrOXEzN1JxODYwUmhLMzAzWm5GZw0KU0p3U0xFTUZUeEwyWlJkeVozMXZoWHgzWTBtYVJnNFFhUExpWVVhcUFoN2JzTDBCdXNDaHR4blZzUWdBUW1NNg0KeTJwdzRGV0RHTkdMajh3MVdFUDNwR3gxaVMvUERncWRCS2VHb0dGQ0diaVJiQTZWWFhqR090clgxYTdVSDV6Tw0KM0tOWjlZTWJ2Q3drZHFRK2xmTUsrY2RPS3YyemE0M3AvUE9MZlpkMFFkNjJOaWZ3RlRaa0dQZHpmTFU1ditzYw0KUHFxTmxHZ1R5bUFseUl2Q3hsNEVTTXMwYjh2OGVJSUZ0YytiMC9qWVNXcjZYUXNDZ2s4NTVJM2ljVk0yN0FXbA0KWTJsVVIyTmZmRGZ4NlpqcEZsdUVFUEthUWxVRzhVVERwT3dBQ0t2NFk0NFQyMUVLZXAzSWhRQWIwT0RjZVgrdA0KSncvT1ZlcWpNV2wyNlAvbVJsWDR2bFRSUHFuaFRtT1Y5bHJiSmRZalZCTndyUHJhDQo=
