# This is with multiple container as a Replica Set using docker.
#spring.mongodb.uri=mongodb://admin:password@authdb1:27017,authdb2:27017,authdb3:27017/authDB?authSource=admin&replicaSet=replicaSet

# This is for a single container using docker.
#spring.mongodb.uri=mongodb://admin:password@localhost:27018/authDB?authSource=admin

spring.mongodb.uri=mongodb://admin:password@authdb-mongo-0.authdb-mongo-svc.authdb.svc.cluster.local:27017,authdb-mongo-1.authdb-mongo-svc.authdb.svc.cluster.local:27017/authDB?authSource=admin&replicaSet=authdb-mongo
spring.application.name=authenticator-service
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG