apiVersion: v1
kind: Service
metadata:
  name: authenticator-service
  labels:
    app: pacman-game
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: pacman-game
    role: authenticator-service
