apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  labels:
    app: pacman-game
spec:
  selector:
    matchLabels:
      app: pacman-game
      role: front-end-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: pacman-game
        role: front-end-gateway
    spec:
      containers:
        - name: front-end
          image: front-end:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MATCHMAKER_URI
              value: https://65095699-bfad-4faf-84a2-557996a0f3f3.mock.pstmn.io
              #value: "http://matchmaker:8080" TODO: UNCOMMENT AFTER TEST
            - name: AUTHENTICATOR_URI
              value: https://d6cb25a1-cac4-41b5-8136-14902491cb37.mock.pstmn.io
              #value: "http://authenticator-service:8080" TODO: UNCOMMENT AFTER TEST
            - name: QUERIES_URI
              value: https://8b3f4688-e340-4c35-a04a-332dd5ecaabc.mock.pstmn.io
              #value: "http://queries-service:8080" TODO: UNCOMMENT AFTER TEST
