# Defines the namespace for the long-term db
apiVersion: v1
kind: Namespace
metadata:
  name: longdb

---

# Defines the configuration for the pods to be done on the startup.
apiVersion: v1
kind: ConfigMap
metadata:
  name: longdb-config
  namespace: longdb
data:
  create_user.sh: |
    #!/bin/bash
    if [ "$HOSTNAME" == "longdb-0" ]; then
      mongosh admin --eval "rs.initiate({_id: 'replicaSet', members: [{ _id: 0, host: 'longdb-0.long-mongo.longdb.svc.cluster.local:27017', priority: 2 }]})"
      sleep 5;

      mongosh admin --eval "db.getSiblingDB('admin').createUser({user: '$MONGO_INITDB_ROOT_USERNAME', pwd: '$MONGO_INITDB_ROOT_PASSWORD', roles: [{ role: 'root', db: 'admin' }]})"
      
      mongosh longdb-0.long-mongo.longdb.svc.cluster.local:27017 -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase admin --eval "db.getSiblingDB('statsDB').createCollection('stats');"
    else
      sleep 15;
      mongosh longdb-0.long-mongo.longdb.svc.cluster.local:27017 -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase admin --eval "rs.add({ host: '${HOSTNAME}.long-mongo.longdb.svc.cluster.local:27017', priority: 1 })"
    fi;

---

# Defines the file containing the replica key.
apiVersion: v1
kind: ConfigMap
metadata:
  name: replica-key
  namespace: longdb
data:
  # Created with openssl rand base64 100
  replica.key: |
    RxewuefQ0bFRFeTwSBXEUdegN1yBuwHCqF3YdTgOjWrqVkvI491ol8kytXUcA8UXPN9AE43wijPE3rCj16yxZhh89pK/nUqK5SVKlLQkdYk4eOih612JL7QX6qWHKOJKcU4rYg==

---

# Defines the username and password of root user.
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: longdb-secret
  namespace: longdb
data:
  # admin in Base64
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  # password in Base64
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=

---

# Headless service for MongoDB pods.
apiVersion: v1
kind: Service
metadata:
  name: long-mongo
  namespace: longdb
  labels:
    app: long-mongo
spec:
  ports:
    - port: 27017         # Incoming traffic at port 27017
      targetPort: 27017   # Redirect the incoming traffic to port 27017 on pods.
  clusterIP: None         # Headleass service.
  selector:
    app: long-mongo

---

# Defines the StatefulSet containing all the pods that work for the replica set.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: longdb          # Pod name.
  namespace: longdb
spec:
  serviceName: long-mongo   # Service name.
  replicas: 3
  selector:
    matchLabels:
      app: long-mongo
  template:
    metadata:
      labels:
        app: long-mongo
    spec:
      containers:
        - name: longdb
          image: mongo:latest
          command:
            - /bin/bash
            - -c
            - |
              /data/mongodbinit/create_user.sh &
              mongod --replSet=replicaSet --bind_ip_all --auth --keyFile=/key/replica.key;
          #command: ["mongod", "--replSet", "replicaSet", "--keyFile", "/key/replica.key", "--bind_ip_all"]
          #command: ["/home/mongodb/permission.sh", "docker-entrypoint.sh", "mongod", "--replSet", "replicaSet", "--keyFile", "/key/replica.key", "--bind_ip_all"]
          env:
            - name: REPLICA_KEY_DIR
              value: /key
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: longdb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: longdb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-long      # PersistantVolumeClaim
              mountPath: /data/db
            - name: replicakey
              mountPath: /key
              readOnly: true
            - name: mongodb-init
              mountPath: /data/mongodbinit
      volumes:
        - name: replicakey
          configMap:
            name: replica-key
            defaultMode: 0600
        - name: mongodb-init
          configMap:
            name: longdb-config
            defaultMode: 0777
  volumeClaimTemplates:             # Defines a PersistentVolumeClaim
    - metadata:
        name: mongo-long
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 1Gi