# Defines the username and password of root user.
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: longdb-secret
  namespace: longdb
data:
  # admin in Base64
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  # password in Base64
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=