# TODO: The longTermDB needs to be created outside the queries service because
# it will be accessible also by matchmaker and game server manager, but each 
# service can create its own collection.
services:
  queries:
    image: mongo:latest
    container_name: queries
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: longTermDB  # Database to be created on startup
    ports:
      - "27018:27017" # Port changed because possible conflict with MongoDb on local
    volumes:
      #- ./mongo-auth:/data/db //TODO: Define the Volume where to mount the DB.
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro  # Mount init scripts folder
    networks:
      - long_term_db_network

  mongo-express-queries:
    image: mongo-express:latest
    container_name: mongo-express-queries
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@queries:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8082:8081"
    depends_on:
      - queries
    networks:
      - long_term_db_network

networks:
  long_term_db_network:
    driver: bridge