#spring.mongodb.uri=mongodb://admin:password@shortdb1:27017,shortdb2:27017,shortdb3:27017/shortDB?authSource=admin&replicaSet=replicaSet
spring.application.name=matchmaker
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#TODO change the uri