spring.mongodb.uri=mongodb://admin:password@shortdb-0.short-mongo.shortdb.svc.cluster.local:27017,shortdb-1.short-mongo.shortdb.svc.cluster.local:27017,shortdb-2.short-mongo.shortdb.svc.cluster.local:27017/shortDB?authSource=admin&replicaSet=replicaSetShort
spring.application.name=matchmaker
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG