spring.mongodb.uri=mongodb://admin:password@shortdb-mongo-0.shortdb-mongo-svc.shortdb.svc.cluster.local:27017,shortdb-mongo-1.shortdb-mongo-svc.shortdb.svc.cluster.local:27017/shortDB?authSource=admin&replicaSet=shortdb-mongo
spring.application.name=matchmaker
logging.level.org.springframework.security=ERROR
#DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=OFF
logging.level.org.mongodb.driver=ERROR
spring.data.mongodb.auto-index-creation=true