spring.mongodb.uri=mongodb://admin:password@longdb-mongo-0.longdb-mongo-svc.longdb.svc.cluster.local:27017,longdb-mongo-1.longdb-mongo-svc.longdb.svc.cluster.local:27017/statsDB?authSource=admin&replicaSet=longdb-mongo
spring.application.name=queries-service
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG