spring.mongodb.uri=mongodb://admin:password@longdb-mongo-0.longdb-mongo-svc.longdb.svc.cluster.local:27017,longdb-mongo-1.longdb-mongo-svc.longdb.svc.cluster.local:27017/statsDB?authSource=admin&replicaSet=longdb-mongo
spring.application.name=queries-service
logging.level.org.springframework.security=ERROR

logging.level.org.springframework.data.mongodb.core.MongoTemplate=OFF
logging.level.org.mongodb.driver.cluster=ERROR
logging.level.org.mongodb.driver.operation=ERROR
logging.level.org.mongodb.driver.connection=ERROR
spring.data.mongodb.auto-index-creation=true