apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  name: "pacman-server"
spec:
  ports:
    - name: default
      containerPort: 7777
      protocol: TCPUDP
  template:
    metadata:
      labels:
        app: pacman-game
        role: game-server
    spec:
      containers:
        - name: pacman-game-server
          image: pacman-game-server:latest
          imagePullPolicy: IfNotPresent
          args: ["--orchestrated", "--local", "match-01"]
