# Defines the namespace for the authdb
apiVersion: v1
kind: Namespace
metadata:
  name: authdb

---

# Defines the configuration for the authdb containers.
apiVersion: v1
kind: ConfigMap
metadata:
  name: authdb-config
  namespace: authdb
data:
  create_user.sh: |
    #!/bin/bash
    if [ "$HOSTNAME" == "authdb-0" ]; then
      mongosh admin --eval "rs.initiate({_id: 'replicaSet', members: [{ _id: 0, host: 'authdb-0.auth-mongo.authdb.svc.cluster.local:27017', priority: 2 }]})"
      sleep 5;

      mongosh admin --eval "db.getSiblingDB('admin').createUser({user: '$MONGO_INITDB_ROOT_USERNAME', pwd: '$MONGO_INITDB_ROOT_PASSWORD', roles: [{ role: 'root', db: 'admin' }]})"
      
      mongosh authdb-0.auth-mongo.authdb.svc.cluster.local:27017 -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase admin --eval "db.getSiblingDB('authDB').createCollection('auth');"
    else
      sleep 15;
      mongosh authdb-0.auth-mongo.authdb.svc.cluster.local:27017 -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase admin --eval "rs.add({ host: '${HOSTNAME}.auth-mongo.authdb.svc.cluster.local:27017', priority: 1 })"
    fi;

---

# Defines the file containing the replica key.
apiVersion: v1
kind: ConfigMap
metadata:
  name: replica-key
  namespace: authdb
data:
  # Created with openssl rand base64 100
  replica.key: |
    EWP6gDQtL7VtkZBoeO9jmL2oYKihGKRvvl+sAZbrsOumv5KCe/VEmmsZ3olHdcFYIrA31VeirjToZw9ZPrx9OO4WHe9aVYw6q7q2X+sA9VyYRXbTcOYHYmi0l9UgO7v7IVDAmQ==

---

# Defines the username and password of root user.
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: authdb-secret
  namespace: authdb
data:
  # admin in Base64
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  # password in Base64
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=
  # ./replica.key in Base64
  # replica_key: K3QxQkNVKy9TeGR2YjE0aUJ4Y1JKc1FUcEpGZXFnZkNJUmc4VVJvT3VycDdOdEpSM0pxNkM1NjMxS2lvMWh4VQ0KZ2dmSlN2S0NveU5DeE9XWWdLUGhya2pobGdib3FzTStyQkR4M3R5RzBpRlFROWFIcnYzT2llRmJFMXVJT0tJcA0KcXZEY3creFVBenAwY1g4MjJVUU9tZURMUFBxMElhalRndGN3bGdQYVhWU2lwSXFvY2ZVQlhGOGpBMTByTGl0Zw0KNW5xVGFXaUNvbFEyTEZSNlAwNS80VzBGVXlINWhSeXdJelRENnR3aVhTMHBwY00vS0VidHMrSzkxSUM5UWVXTg0KYUFSWm9QdUxQQXN3NklnR0hSN3NqQ1creEgzZ1hMdnhxdDdPZWh4L1ZhN2FQMlFTYUM0cnhBRUtyMUp3YVZhbQ0KVE5LZzJ0NlNhMUtOWlhmS3hDYXoxUkIrbDBDOWtPT2pUcDdIbUxnODJFaHNYa2swQlZGT3Z1R2pxWnFQcDlzMA0KRmhrMUwxYVZFenZ3bGRpc0FmT0ZHdmZ0bVBYSHhwaFZqQmlRRmFXWnRUdWZGRTVDVkpaVGlRSVJOL0dMb1hYeQ0KaEI3RHdzT29NRnRKbmZ5S1R1ZkREQTVjYi9jZUdFdnlKaU1jM256WjBmMnd6MkcvcUNNdWtPbnpScTBsaUM5dQ0KU0JIVW1HenhRWjZObGFtL2s1eHV6RWJ5czltZ3B5dzdrMGVLa1AzMzBUZXh0U0pwWFZTaXoyM1VxRCs4RlZGeQ0Ka1VBNnFMcEEzemF0aTZCUG5rTXZSWWZHT29WMi9jUll0TzhvVWo3TVpTK0JrOXEzN1JxODYwUmhLMzAzWm5GZw0KU0p3U0xFTUZUeEwyWlJkeVozMXZoWHgzWTBtYVJnNFFhUExpWVVhcUFoN2JzTDBCdXNDaHR4blZzUWdBUW1NNg0KeTJwdzRGV0RHTkdMajh3MVdFUDNwR3gxaVMvUERncWRCS2VHb0dGQ0diaVJiQTZWWFhqR090clgxYTdVSDV6Tw0KM0tOWjlZTWJ2Q3drZHFRK2xmTUsrY2RPS3YyemE0M3AvUE9MZlpkMFFkNjJOaWZ3RlRaa0dQZHpmTFU1ditzYw0KUHFxTmxHZ1R5bUFseUl2Q3hsNEVTTXMwYjh2OGVJSUZ0YytiMC9qWVNXcjZYUXNDZ2s4NTVJM2ljVk0yN0FXbA0KWTJsVVIyTmZmRGZ4NlpqcEZsdUVFUEthUWxVRzhVVERwT3dBQ0t2NFk0NFQyMUVLZXAzSWhRQWIwT0RjZVgrdA0KSncvT1ZlcWpNV2wyNlAvbVJsWDR2bFRSUHFuaFRtT1Y5bHJiSmRZalZCTndyUHJhDQo=

---

# Headless service for MongoDB pods.
apiVersion: v1
kind: Service
metadata:
  name: auth-mongo
  namespace: authdb
  labels:
    app: auth-mongo
spec:
  ports:
    - port: 27017         # Incoming traffic at port 27017
      targetPort: 27017   # Redirect the incoming traffic to port 27017 on pods.
  clusterIP: None         # Headleass service.
  selector:
    app: auth-mongo

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authdb          # Pod name.
  namespace: authdb
spec:
  serviceName: auth-mongo   # Service name.
  replicas: 3
  selector:
    matchLabels:
      app: auth-mongo
  template:
    metadata:
      labels:
        app: auth-mongo
    spec:
      containers:
        - name: authdb
          image: mongo:latest
          command:
            - /bin/bash
            - -c
            - |
              /data/mongodbinit/create_user.sh &
              mongod --replSet=replicaSet --bind_ip_all --auth --keyFile=/key/replica.key;
          #command: ["mongod", "--replSet", "replicaSet", "--keyFile", "/key/replica.key", "--bind_ip_all"]
          #command: ["/home/mongodb/permission.sh", "docker-entrypoint.sh", "mongod", "--replSet", "replicaSet", "--keyFile", "/key/replica.key", "--bind_ip_all"]
          env:
            - name: REPLICA_KEY_DIR
              value: /key
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: authdb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authdb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-auth      # PersistantVolumeClaim
              mountPath: /data/db
            - name: replicakey
              mountPath: /key
              readOnly: true
            - name: mongodb-init
              mountPath: /data/mongodbinit
            # - name: config
            #   mountPath: /docker-entrypoint-initdb.d
            # - name: permissions
            #   mountPath: /home/mongodb
      volumes:
        - name: replicakey
          configMap:
            name: replica-key
            defaultMode: 0600
          # secret:
          #   secretName: authdb-secret
          #   defaultMode: 0400
          #   items:
          #     - key: replica_key    # Field in secret.yaml
          #       path: replica.key
        # - name: permissions
        #   configMap:
        #     name: permissions
        #     defaultMode: 0755
        # - name: config
        #   configMap:
        #     name: authdb-config
        #     defaultMode: 0755
        - name: mongodb-init
          configMap:
            name: authdb-config
            defaultMode: 0777
  volumeClaimTemplates:             # Defines a PersistentVolumeClaim
    - metadata:
        name: mongo-auth
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 1Gi
