# https://medium.com/@godfreyifeanyi50/using-a-kubernetes-job-to-automate-mongodb-replica-set-initialization-a-detailed-guide-ea75a5353ed2

apiVersion: batch/v1
kind: Job
metadata:
  name: authdb-setup
  namespace: authdb
spec:
  ttlSecondsAfterFinished: 10   # Time to leave after the script's end. Resources will be free.
  template:
    spec:
      containers:
        - name: authdb-setup
          image: mongo:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              # Name: PodName.ServiceName.Namespace.svc.cluster.local
              m1=authdb-0.auth-mongo.authdb.svc.cluster.local
              m2=authdb-1.auth-mongo.authdb.svc.cluster.local
              m3=authdb-2.auth-mongo.authdb.svc.cluster.local
              port=27017
              
              echo "###### Waiting for ${m1} instance startup.."
              until mongosh --host ${m1}:${port} --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' &>/dev/null; do
                printf '.'
                sleep 1
              done
              echo "\\n###### Working ${m1} instance found, initiating user setup & initializing rs setup.."

              echo "\\n###### Creating the root user"
              mongosh --host ${m1}:${port} admin --eval <<END
                if (!db.getUser('${MONGO_INITDB_ROOT_USERNAME}')) {
                  db.createUser({
                    user:'$MONGO_INITDB_ROOT_USERNAME',
                    pwd:'$MONGO_INITDB_ROOT_PASSWORD',
                    roles:[{role:'root',db:'admin'}]
                  });
                }
              END

              echo "\\n##### setup user + pass and initialize replica sets"
              mongosh --host ${m1}:${port} <<EOF
              var rootUser = '$MONGO_INITDB_ROOT_USERNAME';
              var rootPassword = '$MONGO_INITDB_ROOT_PASSWORD';
              use admin
              db.auth(rootUser, rootPassword);
              var status = {};
              try { status = rs.status(); } catch(e) { status.ok = 0; }

              if (status.ok === 0) {
                var config = {
                  "_id": "replicaSet",
                  "version": 1,
                  "members": [
                      { "_id": 0, "host": "${m1}:${port}", "priority": 2 },
                      { "_id": 1, "host": "${m2}:${port}", "priority": 1 },
                      { "_id": 2, "host": "${m3}:${port}", "priority": 1 }
                  ]
                };
                rs.initiate(config, { force: true });
              }
              EOF

              echo "\\n###### Waiting for ReplicaSet to be up"
              until mongosh --host ${m1}:${port} --eval 'quit(rs.status().ok ? 0 : 2)' &>/dev/null; do
                printf '.'
                sleep 2
              done

              mongosh --host ${m1}:${port} -u "${MONGO_INITDB_ROOT_USERNAME}" -p "${MONGO_INITDB_ROOT_PASSWORD}" --authenticationDatabase admin --eval "
                db.getSiblingDB('authDB').createCollection('auth');
              "

              echo "\n###### Setup completed!!!"
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: authdb-secret
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: authdb-secret
                key: MONGO_INITDB_ROOT_PASSWORD
      restartPolicy: OnFailure