# Defines the StatefulSet containing all the pods that work for the replica set.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shortdb          # Pod name.
  namespace: shortdb
spec:
  serviceName: short-mongo   # Service name.
  replicas: 3
  selector:
    matchLabels:
      app: short-mongo
  template:
    metadata:
      labels:
        app: short-mongo
    spec:
      containers:
        - name: shortdb
          image: mongo:latest
          command:
            - /bin/bash
            - -c
            - |
              /data/mongodbinit/create_user.sh &
              mongod --replSet=replicaSet --bind_ip_all --auth --keyFile=/key/replica.key;
          env:
            - name: REPLICA_KEY_DIR
              value: /key
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: shortdb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shortdb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-short      # PersistantVolumeClaim
              mountPath: /data/db
            - name: replicakey
              mountPath: /key
              readOnly: true
            - name: mongodb-init
              mountPath: /data/mongodbinit
      volumes:
        - name: replicakey
          configMap:
            name: replica-key
            defaultMode: 0600
        - name: mongodb-init
          configMap:
            name: shortdb-config
            defaultMode: 0777
  volumeClaimTemplates:             # Defines a PersistentVolumeClaim
    - metadata:
        name: mongo-short
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 1Gi
