apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-server-manager
  labels:
    app: pacman-game
spec:
  selector:
    matchLabels:
      app: pacman-game
      role: game-server-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: pacman-game
        role: game-server-manager
    spec:
      serviceAccountName: game-server-manager-sa
      containers:
        - name: game-server-manager
          image: game-server-manager:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MATCHMAKER_URI
              value: "http://matchmaker:8080"
            - name: GAMESERVER_IMAGE_NAME
              value: "pacman-game:latest"
            #- name: MIN_TIME_LEFT
            #  value: 8000
            #- name: SHORT_TERM_DB_URI # TODO: uncomment during integration
            #  value: "http://test/test" # TODO: put correct value
            #- name: LONG_TERM_DB_URI # TODO: uncomment during integration
            #  value: "http://test1/test" # TODO: put correct value
