apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-server-manager
  labels:
    app: pacman-game
spec:
  selector:
    matchLabels:
      app: pacman-game
      role: game-server-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: pacman-game
        role: game-server-manager
    spec:
      serviceAccountName: game-server-manager-sa
      containers:
        - name: game-server-manager
          image: game-server-manager:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MATCHMAKER_URI
              value: "http://matchmaker:8080"
            - name: GAMESERVER_IMAGE_NAME
              value: "pacman-game:latest"
            #- name: MIN_TIME_LEFT
            #  value: 8000
            - name: SHORT_TERM_DB_URI
              value: "mongodb://admin:password@shortdb-0.short-mongo.shortdb.svc.cluster.local:27017,shortdb-1.short-mongo.shortdb.svc.cluster.local:27017,shortdb-2.short-mongo.shortdb.svc.cluster.local:27017/shortDB?authSource=admin&replicaSet=replicaSet"
            - name: LONG_TERM_DB_URI
              value: "mongodb://admin:password@longdb-0.long-mongo.longdb.svc.cluster.local:27017,longdb-1.long-mongo.longdb.svc.cluster.local:27017,longdb-2.long-mongo.longdb.svc.cluster.local:27017/statsDB?authSource=admin&replicaSet=replicaSet"
