apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: authdb-mongo
  namespace: authdb
spec:
  type: ReplicaSet
  members: 3
  arbiters: 1
  version: "8.0.0"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: secret
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: scram-authdb
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: authdb
              # resources:
              #   requests:
              #     cpu: 250m
              #     memory: 512Mi
              #   limits:
              #     cpu: 1
              #     memory: 2Gi
              ports:
                    - containerPort: 27017
              volumeMounts:
                - name: mongo-auth      # PersistantVolumeClaim
                  mountPath: /data/db
  volumeClaimTemplates:             # Defines a PersistentVolumeClaim
    - metadata:
        name: mongo-auth
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi


---
# Defines the username and password of root user.
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secret
  namespace: authdb
stringData:
  password: password